# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hABxCZahvhKQ6yL9VWziouoyt89BSscL

# Proyek Analisis Data: [E-Commerce Public Dataset]
- **Nama:** [Alviyatur Rahmaniyah]
- **Email:** [alviyaturrahmaniyah@gmail.com]
- **ID Dicoding:** [CDCC229D6X1609]

## Menentukan Pertanyaan Bisnis

- Bagaimana perkembangan jumlah transaksi dan pendapatan dari waktu ke waktu pada data e-commerce ini selama periode tahun 2016 hingga 2018?
- Bagaimana karakteristik pelanggan berdasarkan RFM (Recency, Frequency, Monetary) berdasarkan data transaksi hingga akhir tahun 2018?

## Import Semua Packages/Library yang Digunakan

**Import library**

Pada tahap ini dilakukan import library yang digunakan untuk proses analisis data, seperti pandas untuk manipulasi data, numpy untuk perhitungan numerik, serta matplotlib dan seaborn untuk visualisasi
"""

# Import library yang dibutuhkan
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

"""## Data Wrangling

### Gathering Data

**Load Dataset**

Tahap ini dilakukan untuk memuat seluruh tabel dataset yang diperlukan ke dalam dataframe.
"""

import os

print(os.getcwd())
print(os.listdir())

!find . -name "products_dataset.csv"

# Load dataset utama
orders = pd.read_csv('orders_dataset.csv')
order_items = pd.read_csv('order_items_dataset.csv')
products = pd.read_csv('products_dataset.csv')
customers = pd.read_csv('customers_dataset.csv')

"""**Insight:**
- Dataset berhasil dimuat tanpa error.
- Terdapat empat dataset utama yaitu orders, order_items, products, dn customers.
- Dataset siap untuk tahap eksplorasi lebih lanjut.

### Assessing Data

**Assessing Data**

Pada tahap ini, dilakukan pemeriksaan kualitas data untuk mendeteksi adanya missing values, duplikasi data, atau ketidaksesuaian tipe data.
"""

# Cek isi awal dataset
orders.head()
order_items.head()
products.head()
customers.head()

# Cek tipe data dan missing value
orders.info()
order_items.info()
products.info()
customers.info()

# Statistik dasar (numerik)
orders.describe()
order_items.describe()
products.describe()
customers.describe()

"""**Insight:**
- Dataset terdiri dari empat tabel utama, yaitu orders (99.441 data), order_items (112.650 data), products (32.951 data), dan customers (99.441 data)
- Pada dataset orders ditemukan beberapa missing values, terutama pada order_approved_at, order_delivered_carrier_date, dan order_delivered.
- Dataset products juga memiliki missing values pada beberapa atribut seperti: product_category_name, product_name_length, dan atribut dimensi produk, yang perlu ditangani sebelum analisis lebih lanjut.
- Dataset order_items dan customers relatif bersih karena tidak ditemukan missing values.
- Tipe data pada dataset orders masih berupa object, termasuk kolom tanggal, sehingga perlu dilakukan konversi ke tipe datetime untuk analisis waktu.
- Dataset order_items memiliki variabel numerik seperti price dan freight_value yang dapat digunakan untuk analisis nilai transaksi dan biaya pengiriman.
- Berdasarkan statistik deskriptif pada dataset customers, terlihat bahwa distribusi customer_zip_code_prefix cukup bervariasi, menunjukkan pelanggan berasal dari berbagai wilayah.

### Cleaning Data

Tahap ini mencakup perbaikan tipe data pada kolom tanggal, penanganan nilai kosong, dan pembersihan data duplikat agar siap dianalisis.

Cek Missing value dan Duplikat
"""

# Cek missing value dataset
print("=== Orders ===")
print(orders.isnull().sum(), "\n")

print("=== Order Items ===")
print(order_items.isnull().sum(), "\n")

print("=== Products ===")
print(products.isnull().sum(), "\n")

print("=== Customers ===")
print(customers.isnull().sum(), "\n")

# Cek duplikat
print("=== Duplikat ===")
print("Orders:", orders.duplicated().sum())
print("Order items:", order_items.duplicated().sum())

"""**Insight:**
- Pada dataset orders ditemukan beberapa missing values, terutama pada kolom order_approved_at (160 data), order_delivered_carrier_date (1.783 data), dan order_delivered_customer_date (2.965 data). Hal ini kemungkinan disebabkan oleh pesanan yang belum diproses, belum dikirim, atau belum sampai ke pelanggan.

- Dataset products juga memiliki missing values yang cukup signifikan pada beberapa kolom, seperti product_category_name, product_name_lenght, product_description_lenght, dan product_photos_qty (masing-masing sebanyak 610 data). Selain itu, terdapat sedikit missing values pada atribut dimensi produk (2 data).

- Dataset order_items dan customers tidak memiliki missing values, sehingga dapat dikatakan cukup bersih dan siap digunakan untuk analisis lebih lanjut.

- Tidak ditemukan data duplikat pada dataset orders maupun order_items, yang menunjukkan bahwa data relatif konsisten dan tidak terdapat redundansi data.

- Secara keseluruhan, permasalahan utama pada data terletak pada missing values di dataset orders dan products, sehingga diperlukan penanganan lebih lanjut seperti imputasi atau penghapusan data sebelum dilakukan analisis lanjutan.
"""

# Hapus duplikat di semua dataset
orders = orders.drop_duplicates()
order_items = order_items.drop_duplicates()
products = products.drop_duplicates()
customers = customers.drop_duplicates()

# Kolom tanggal diubah ke datetime
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

# Kolom numeric
order_items['price'] = pd.to_numeric(order_items['price'], errors='coerce')
order_items['freight_value'] = pd.to_numeric(order_items['freight_value'], errors='coerce')

"""**Insight:**
- Proses pembersihan data diawali dengan penghapusan data duplikat pada seluruh dataset (orders, order_items, products, dan customers) untuk memastikan tidak terdapat data yang redundan. Hal ini penting agar hasil analisis tidak bias akibat perhitungan data yang berulang.

- Selanjutnya, dilakukan konversi tipe data pada kolom-kolom bertipe tanggal di dataset orders menjadi format datetime. Langkah ini bertujuan agar data waktu dapat diolah dengan lebih akurat, terutama untuk analisis berbasis waktu seperti tren transaksi dan perhitungan recency.

- Selain itu, dilakukan konversi tipe data numerik pada kolom price dan freight_value di dataset order_items. Penggunaan parameter errors='coerce' memastikan bahwa nilai yang tidak valid akan diubah menjadi NaN, sehingga dapat ditangani pada tahap selanjutnya.

- Secara keseluruhan, proses cleaning ini bertujuan untuk meningkatkan kualitas dan konsistensi data, sehingga data menjadi lebih siap untuk tahap analisis lanjutan seperti eksplorasi data (EDA) dan pemodelan.
"""

# Buang transaksi yang dibatalkan
orders = orders[orders['order_status'] != 'canceled']

# Pastikan tidak ada baris duplikat tersisa
orders = orders.drop_duplicates()

"""**Insight:**
- Dilakukan penghapusan transaksi dengan status "canceled" pada dataset orders untuk memastikan bahwa analisis hanya mencakup transaksi yang benar-benar terjadi.

- Penghapusan data transaksi yang dibatalkan penting karena transaksi tersebut tidak menghasilkan pendapatan dan dapat menyebabkan bias dalam analisis, terutama pada perhitungan jumlah transaksi dan total revenue.

- Setelah proses filtering, dilakukan kembali pengecekan dan penghapusan duplikat untuk memastikan tidak ada data yang redundan yang tersisa.

- Dengan langkah ini, dataset menjadi lebih representatif terhadap aktivitas transaksi yang valid, sehingga hasil analisis yang diperoleh menjadi lebih akurat dan relevan.
"""

# Gabungkan semua dataset utama
df_clean = orders.merge(order_items, on='order_id', how='left') \
                 .merge(products, on='product_id', how='left') \
                 .merge(customers, on='customer_id', how='left')

# Cek hasil
df_clean.head()
df_clean.info()

"""**Insight:**
- Seluruh dataset utama (orders, order_items, products, dan customers) berhasil digabungkan menjadi satu dataframe terintegrasi menggunakan metode left join, sehingga informasi transaksi, produk, dan pelanggan dapat dianalisis secara menyeluruh dalam satu tabel.

- Hasil penggabungan menghasilkan 112.719 baris data dengan 26 kolom, yang mencakup berbagai informasi penting seperti detail pesanan, harga, atribut produk, serta lokasi pelanggan.

- Tipe data pada sebagian besar kolom telah sesuai, terutama kolom tanggal yang sudah dalam format datetime, sehingga siap digunakan untuk analisis berbasis waktu.

- Namun, masih terdapat beberapa missing values pada kolom hasil join, seperti pada order_item_id, product_id, serta atribut produk (misalnya product_category_name). Hal ini kemungkinan disebabkan oleh penggunaan left join, di mana tidak semua data pada tabel utama memiliki pasangan di tabel lainnya.

- Secara keseluruhan, dataset hasil penggabungan sudah cukup lengkap dan terstruktur dengan baik, sehingga dapat digunakan untuk analisis lanjutan seperti eksplorasi data (EDA), analisis tren, maupun segmentasi pelanggan.
"""

# Missing value terakhir
df_clean.isnull().sum()

# Sample beberapa baris
df_clean.sample(5)

"""**Insight:**
- Setelah proses pembersihan dan penggabungan data, masih terdapat beberapa missing values pada beberapa kolom, terutama pada atribut terkait produk dan proses pengiriman. Hal ini kemungkinan disebabkan oleh data yang tidak lengkap sejak awal atau hasil dari proses penggabungan (join) antar dataset.

- Missing values pada kolom terkait pengiriman, seperti order_delivered_carrier_date dan order_delivered_customer_date, dapat mengindikasikan adanya pesanan yang belum sepenuhnya selesai atau keterbatasan pencatatan data.

- Sementara itu, missing values pada atribut produk seperti product_category_name dan deskripsi produk menunjukkan bahwa tidak semua produk memiliki informasi yang lengkap.

- Berdasarkan hasil sampling data, secara umum struktur dataset sudah konsisten dan setiap baris telah merepresentasikan satu item transaksi dengan informasi yang cukup lengkap, mencakup data pesanan, produk, dan pelanggan.

- Secara keseluruhan, dataset sudah berada dalam kondisi yang cukup baik dan siap digunakan untuk analisis lanjutan, meskipun masih diperlukan penanganan tambahan terhadap missing values tertentu agar hasil analisis menjadi lebih optimal.

## Exploratory Data Analysis (EDA)

### Explore data untuk memahami distribusi variabel, mendeteksi outlier, dan melihat korelasi antar fitur numerik.
"""

# 1. EDA Univariate: Distribusi Harga dan Ongkir
plt.figure(figsize=(15, 5))
plt.subplot(1, 2, 1)
sns.histplot(df_clean['price'], kde=True, bins=30, color='skyblue')
plt.title('Distribusi Harga Produk')

plt.subplot(1, 2, 2)
sns.histplot(df_clean['freight_value'], kde=True, bins=30, color='orange')
plt.title('Distribusi Biaya Pengiriman')
plt.show()

# Boxplot untuk cek Outliers (Sangat diminta Reviewer)
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.boxplot(x=df_clean['price'], color='lightcoral')
plt.title('Boxplot Harga (Outlier Check)')

plt.subplot(1, 2, 2)
sns.boxplot(x=df_clean['freight_value'], color='lightgreen')
plt.title('Boxplot Freight Value (Outlier Check)')
plt.show()

# 2. EDA Kategorikal: Top 10 Kategori Produk
plt.figure(figsize=(10, 6))
top_categories = df_clean['product_category_name'].value_counts().head(10)
sns.barplot(x=top_categories.values, y=top_categories.index, palette='viridis')
plt.title('Top 10 Kategori Produk Terpopuler')
plt.show()

# 3. EDA Multivariate: Korelasi antar variabel numerik (WAJIB ADA)
plt.figure(figsize=(10, 8))
numeric_cols = df_clean.select_dtypes(include=['number'])
correlation_matrix = numeric_cols.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Heatmap Korelasi Variabel Numerik')
plt.show()

"""**Insight:**

**Distribusi Variabel Numerik & Outliers:**
 - Variabel Price dan Freight Value memiliki distribusi yang sangat miring ke kanan (right-skewed). Sebagian besar transaksi berada pada rentang harga rendah, namun terdapat banyak outliers (anomali data) pada harga tinggi yang mencapai angka di atas 6.000.

- Hal ini menunjukkan bahwa meskipun rata-rata transaksi bernilai kecil, terdapat segmen produk eksklusif atau mewah yang memberikan kontribusi pendapatan besar namun dengan frekuensi rendah.

**Analisis Kategorikal:**

- Kategori produk "cama_mesa_banho" (bed, bath & table) merupakan kategori dengan jumlah transaksi tertinggi, disusul oleh "beleza_saude" dan "esporte_lazer". Ini menunjukkan dominasi produk kebutuhan rumah tangga dan kesehatan dalam ekosistem e-commerce ini.

**Analisis Korelasi (Heatmap):**

- Terdapat korelasi positif yang cukup kuat antara product_weight_g dengan freight_value (0.61). Hal ini logis karena berat produk merupakan faktor utama penentu biaya pengiriman.

- Korelasi antara price dan freight_value sebesar 0.41, menunjukkan bahwa semakin mahal harga produk, ada kecenderungan biaya kirimnya juga sedikit lebih tinggi.

- Variabel lain seperti jumlah foto atau panjang deskripsi tidak memiliki korelasi signifikan terhadap harga maupun ongkos kirim.

### Menyiapkan data tren bulanan dan menghitung profil RFM (Recency, Frequency, Monetary) untuk analisis perilaku pelanggan.
"""

# Buat kolom bulan & tahun
df_clean['year_month'] = df_clean['order_purchase_timestamp'].dt.to_period('M')

# Agregasi Tren Bulanan
monthly_orders = df_clean.groupby('year_month')['order_id'].nunique().reset_index()
monthly_orders.rename(columns={'order_id':'num_orders'}, inplace=True)
monthly_revenue = df_clean.groupby('year_month')['price'].sum().reset_index()

# Gabungkan data tren transaksi dan revenue
monthly_trend = monthly_orders.merge(
    monthly_revenue,
    on='year_month'
)

monthly_trend.to_csv(
    'monthly_trend.csv',
    index=False
)

# Hitung RFM
snapshot_date = df_clean['order_purchase_timestamp'].max() + pd.Timedelta(days=1)
rfm = df_clean.groupby('customer_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'price': 'sum'
}).reset_index()
rfm.columns = ['customer_id', 'Recency', 'Frequency', 'Monetary']

# Preview
print("Preview RFM Table:")
print(rfm.head())

"""**Insight:**

**Profil Transaksi Pelanggan:**
- Berdasarkan preview tabel RFM, terlihat bahwa mayoritas pelanggan dalam sampel ini memiliki nilai Frequency sebanyak 1. Hal ini mengindikasikan bahwa sebagian besar pelanggan adalah one-time buyers atau baru melakukan satu kali transaksi dalam periode 2016-2018.

- Nilai Recency yang bervariasi (rentang 154 hingga 552 hari) menunjukkan adanya perbedaan yang cukup jauh antara pelanggan yang baru saja bertransaksi dengan pelanggan yang sudah lama tidak aktif (churned customers).

- Nilai Monetary menunjukkan variasi pengeluaran mulai dari 54.90 hingga 179.99. Hal ini menandakan adanya segmentasi pelanggan berdasarkan daya beli, yang nantinya dapat dikelompokkan menjadi segmen Low, Medium, dan High Spenders.

**Tend Penjualan:**

- Pembuatan kolom year_month memungkinkan kita untuk melakukan analisis time-series. Melalui pengelompokan ini, kita dapat mengidentifikasi pola musiman atau lonjakan transaksi pada bulan-bulan tertentu selama periode observasi.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana perkembangan jumlah transaksi dan pendapatan dari waktu ke waktu pada data e-commerce ini selama periode tahun 2016 hingga 2018?
"""

# Buat kolom timestamp
monthly_orders_plot = monthly_orders.copy()
monthly_orders_plot['year_month_ts'] = monthly_orders_plot['year_month'].dt.to_timestamp()

monthly_revenue_plot = monthly_revenue.copy()
monthly_revenue_plot['year_month_ts'] = monthly_revenue_plot['year_month'].dt.to_timestamp()

# Dual axis chart
plt.figure(figsize=(14,6))

sns.lineplot(
    data=monthly_orders_plot,
    x='year_month_ts',
    y='num_orders',
    marker='o',
    label='Jumlah Transaksi'
)

sns.lineplot(
    data=monthly_revenue_plot,
    x='year_month_ts',
    y='price',
    marker='o',
    label='Pendapatan'
)

plt.title('Monthly Transaction and Revenue Trends')
plt.xlabel('Month')
plt.ylabel('Value')
plt.xticks(rotation=45)
plt.legend()

plt.show()

"""**Insight:**
- Pendapatan mencapai puncaknya pada November 2017 sebelum mengalami fluktuasi pada periode berikutnya.

- Terdapat perbedaan skala yang sangat kontras antara jumlah transaksi dan pendapatan. Hal ini mengindikasikan bahwa model bisnis sangat bergantung pada nilai per transaksi yang tinggi (High Average Order Value) daripada volume transaksi yang masif.

- Lonjakan tertinggi tercatat pada November 2017. Ini menunjukkan adanya momentum sukses, kemungkinan besar dipicu oleh promo akhir tahun atau kampanye besar yang berhasil menarik transaksi bernilai tinggi.

- Setelah mencapai puncak, pendapatan cenderung fluktuatif di tahun 2018. Meskipun sempat turun, level pendapatan di 2018 secara umum masih jauh lebih tinggi dibandingkan rata-rata pendapatan di tahun 2017 awal.

### Pertanyaan 2: Bagaimana karakteristik pelanggan berdasarkan RFM (Recency, Frequency, Monetary) berdasarkan data transaksi hingga akhir tahun 2018?
"""

plt.figure(figsize=(12,4))
sns.histplot(rfm['Recency'], bins=30, kde=True, color='blue')
plt.title('Distribusi Recency')
plt.xlabel('Hari Sejak Transaksi Terakhir')
plt.show()

plt.figure(figsize=(12,4))
sns.histplot(rfm['Frequency'], bins=30, kde=True, color='orange')
plt.title('Distribusi Frequency')
plt.xlabel('Jumlah Transaksi')
plt.show()

plt.figure(figsize=(12,4))
sns.histplot(rfm['Monetary'], bins=30, kde=True, color='green')
plt.title('Distribusi Monetary')
plt.xlabel('Total Pengeluaran')
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(data=rfm, x='Frequency', y='Monetary')
plt.title('Frequency vs Monetary')
plt.xlabel('Jumlah Transaksi')
plt.ylabel('Total Pengeluaran')
plt.show()

"""**Insight:**
- Distribusi Recency menunjukkan pola yang tersebar luas, dengan puncak kepadatan tertinggi berada di sekitar 280-300 hari. Ini menandakan banyak pelanggan yang sudah tidak bertransaksi selama hampir satu tahun.

- Grafik Frequency menunjukkan batang tunggal yang sangat dominan di angka 1. Hal ini membuktikan bahwa hampir seluruh pelanggan hanya melakukan satu kali transaksi tanpa adanya pembelian berulang (repeat order).

- Distribusi Monetary sangat miring ke kanan, di mana mayoritas pengeluaran pelanggan terkonsentrasi di angka rendah, namun terdapat beberapa pelanggan dengan total belanja sangat besar hingga mencapai 14.000.

- Scatter plot Frequency vs Monetary membentuk satu garis vertikal lurus pada titik 1.0. Hal ini mengonfirmasi bahwa nilai pendapatan saat ini sepenuhnya bergantung pada variasi pengeluaran dari transaksi tunggal pelanggan baru.

- Secara keseluruhan, profil pelanggan didominasi oleh tipe pelanggan satu kali belanja yang sudah cukup lama tidak aktif, sehingga diperlukan strategi untuk meningkatkan retensi dan frekuensi belanja.

## Analisis Lanjutan (Opsional)

### Segmentasi Pelanggan dengan RFM Analysis

RFM Analysis bertujuan mengelompokkan pelanggan berdasarkan perilaku pembelian:
- **Recency**: Hari sejak transaksi terakhir
- **Frequency**: Jumlah transaksi
- **Monetary**: Total pengeluaran
"""

# Buat RFM Score
rfm['R_Score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])  # Recency: lebih rendah lebih baik
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])

# Gabungkan jadi RFM Score
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

rfm.head()

def segment_customer(row):
    if row['R_Score'] >= 4 and row['F_Score'] >= 3 and row['M_Score'] >= 3:
        return 'Champions'
    elif row['R_Score'] >= 3 and row['F_Score'] >= 3:
        return 'Loyal Customers'
    elif row['R_Score'] >= 3:
        return 'Potential Loyalist'
    elif row['R_Score'] <= 2 and row['F_Score'] >= 3:
        return 'At Risk'
    else:
        return 'Hibernating'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

plt.figure(figsize=(10,5))

segment_count = rfm['Segment'].value_counts()

sns.barplot(
    x=segment_count.index,
    y=segment_count.values
)

plt.title("Customer Segmentation Based on RFM")
plt.xlabel("Segment")
plt.ylabel("Number of Customers")
plt.xticks(rotation=20)
plt.show()

rfm.head()

top_customers = rfm.sort_values(
    by='Monetary',
    ascending=False
).head(10)

sns.barplot(
    data=top_customers,
    x='Monetary',
    y='customer_id'
)

"""**Insight:**
- Segmentasi Pelanggan Berdasarkan Skor RFM: Berdasarkan skor RFM yang telah dihitung, pelanggan berhasil dikelompokkan ke dalam beberapa segmen seperti Champions, Loyal Customers, dan At Risk. Ini memberikan gambaran yang jauh lebih jelas daripada sekadar melihat angka mentah.

- Dominasi Segmen Tertentu: Terlihat bahwa terdapat jumlah yang signifikan pada segmen tertentu (seperti Hibernating atau At Risk), yang mengonfirmasi temuan sebelumnya bahwa banyak pelanggan sudah lama tidak melakukan transaksi kembali.

- Proporsi Pelanggan 'Champions': Visualisasi menunjukkan persentase pelanggan setia (Champions) yang mungkin kecil secara jumlah, namun merupakan aset paling berharga karena memiliki skor RFM tertinggi di semua aspek.

- Strategi Pemasaran Terarah: Dengan adanya analisis lanjutan ini, bisnis kini memiliki landasan untuk memberikan perlakuan yang berbeda pada tiap segmen, misalnya memberikan diskon retensi untuk segmen At Risk atau program loyalitas eksklusif untuk segmen Champions.

### Segmentasi Tambahan dengan Binning
Pelanggan dikelompokkan berdasarkan:
- Total Pengeluaran (Monetary)
- Jumlah Transaksi (Frequency)
"""

# Binning Monetary
if rfm['Monetary'].nunique() > 1:
    monetary_bins = np.linspace(rfm['Monetary'].min(), rfm['Monetary'].max(), 5)
    rfm['Monetary_Bin'] = pd.cut(rfm['Monetary'], bins=monetary_bins, labels=['Low','Medium','High','Very High'], include_lowest=True)
else:
    rfm['Monetary_Bin'] = 'Medium'

# Binning Frequency
if rfm['Frequency'].nunique() > 1:
    freq_bins = np.linspace(rfm['Frequency'].min(), rfm['Frequency'].max(), 5)
    rfm['Frequency_Bin'] = pd.cut(rfm['Frequency'], bins=freq_bins, labels=['Low','Medium','High','Very High'], include_lowest=True)
else:
    rfm['Frequency_Bin'] = 'Low'

# Visualisasi
plt.figure(figsize=(10,6))
sns.scatterplot(data=rfm, x='Frequency', y='Monetary', hue='Monetary_Bin', style='Frequency_Bin', palette='viridis', s=100)
plt.title('Segmentasi Pelanggan: Frequency vs Monetary')
plt.xlabel('Jumlah Transaksi')
plt.ylabel('Total Pengeluaran')
plt.legend(bbox_to_anchor=(1.05,1), loc='upper left')
plt.show()

"""**Insight:**
- Segmentasi Pelanggan Berdasarkan Skor RFM: Berdasarkan perhitungan skor RFM, pelanggan telah dikelompokkan ke dalam beberapa segmen strategis untuk memahami perilaku mereka secara lebih mendalam.

- Dominasi Segmen 'Hibernating': Segmen Hibernating memiliki jumlah pelanggan yang sangat dominan dibandingkan segmen lainnya, yang mengonfirmasi bahwa banyak pelanggan lama yang sudah tidak aktif kembali.

- Proporsi Pelanggan 'Champions' dan 'Loyal': Terdapat kelompok pelanggan Champions dan Loyal Customers yang meskipun jumlahnya tidak sebanyak segmen lain, mereka merupakan aset penting bagi pendapatan bisnis.

- Distribusi Nilai RFM per Segmen: Visualisasi menunjukkan bahwa setiap segmen memiliki karakteristik unik, seperti segmen Champions yang memiliki skor tinggi pada ketiga aspek (Recency, Frequency, Monetary).

- Landasan Strategi Pemasaran: Analisis ini memberikan dasar bagi bisnis untuk melakukan pendekatan yang berbeda, seperti memberikan insentif khusus bagi pelanggan di segmen At Risk agar tidak berpindah ke kompetitor.

## Conclusion

- Perkembangan bisnis menunjukkan tren pertumbuhan yang sangat positif dan signifikan, terutama mulai awal tahun 2017 hingga pertengahan 2018. Puncak performa terjadi pada November 2017, di mana pendapatan melonjak drastis hingga menyentuh angka 1 juta. Meskipun jumlah transaksi bulanan secara skala jauh lebih kecil dibandingkan nilai moneternya, keduanya bergerak selaras menunjukkan ekspansi pasar yang kuat selama periode tersebut.

- Karakteristik utama pelanggan hingga akhir 2018 adalah didominasi oleh pembeli satu kali (one-time buyers) dengan tingkat loyalitas (frekuensi) yang rendah. Dari sisi Recency, banyak pelanggan yang sudah tidak aktif dalam jangka waktu lama (puncak kepadatan di sekitar 280-300 hari). Melalui segmentasi RFM, terlihat bahwa mayoritas pelanggan masuk dalam kategori Hibernating, namun terdapat kelompok Champions yang memiliki nilai moneter tinggi yang menjadi aset berharga bagi perusahaan.
"""

rfm.to_csv("main_data.csv", index=False)

# Cek apakah variabelnya ada
print(monthly_orders.head())
print(monthly_revenue.head())

# Buat file CSV
monthly_trend = monthly_orders.merge(
    monthly_revenue,
    on='year_month'
)

print(monthly_trend.head())

monthly_trend.to_csv(
    "monthly_trend.csv",
    index=False
)

print("File berhasil dibuat!")

import os
print(os.listdir())